=== NicolaSabino/DP2_Assignment1/xsd/rnsInfo.xsd
<?xml version="1.0"?>
<xsd:schema  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!-- GLOBAL ELEMENT DECLARATION -->
	<xsd:element name="roadNavigationSystem">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="vehicle" type="vehicleType" maxOccurs="unbounded" minOccurs="0"/>
				<xsd:element name="place" type="placeType" maxOccurs="unbounded" minOccurs="0">
					<!-- unique #1 -->
					<xsd:unique name="serviceUniqueness">
						<xsd:selector xpath="parkingArea/service"/>
						<xsd:field xpath="."/>
					</xsd:unique>
				</xsd:element>
				<xsd:element name="connection" type="connectionType" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
		<!-- key #1 -->
		<xsd:key name="vehicleKey">
			<xsd:selector xpath="vehicle"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
		<!-- key #2 -->
		<xsd:key name="placeKey">
			<xsd:selector xpath="place"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
		<!-- reference #1 -->
		<xsd:keyref name="positionRef" refer="placeKey">
			<xsd:selector xpath="vehicle" />
			<xsd:field xpath="@position" />
		</xsd:keyref>
		<!-- reference #2 -->
		<xsd:keyref name="fromRef" refer="placeKey">
			<xsd:selector xpath="vehicle" />
			<xsd:field xpath="@from" />
		</xsd:keyref>
		<!-- reference #3 -->
		<xsd:keyref name="toRef" refer="placeKey">
			<xsd:selector xpath="vehicle" />
			<xsd:field xpath="@to" />
		</xsd:keyref>
		<!-- reference #4 -->
		<xsd:keyref name="connectionFromRef" refer="placeKey">
			<xsd:selector xpath="connection"/>
			<xsd:field xpath="@from"/>
		</xsd:keyref>
		<!-- reference #5 -->
		<xsd:keyref name="connectionToRef" refer="placeKey">
			<xsd:selector xpath="connection"/>
			<xsd:field xpath="@to"/>
		</xsd:keyref>
		<!-- reference #6 -->
		<xsd:keyref name="nextPlaceRef" refer="placeKey">
			<xsd:selector xpath="place/nextPlace"/>
			<xsd:field xpath="."/>
		</xsd:keyref>
		<!-- unique #2 -->
		<xsd:unique name="road_name_uniqueness">
			<xsd:selector xpath="place/roadSegment"/>
			<xsd:field xpath="@name"/>
			<xsd:field xpath="@road"/>
		</xsd:unique>
		<!-- unique #3 -->
		<xsd:unique name="connection_uniqueness">
			<xsd:selector xpath="connection"/>
			<xsd:field xpath="@from"/>
			<xsd:field xpath="@to"/>
		</xsd:unique>
	</xsd:element>
	<!-- TYPE DEFINITIONS -->
	<xsd:complexType name="connectionType">
		<xsd:attribute name="from" type="xsd:string" use="required"/> 	<!-- key -->
		<xsd:attribute name="to" type="xsd:string" use="required"/>		<!-- key -->
	</xsd:complexType>
	<xsd:complexType name="vehicleType">
		<xsd:attribute name="id" type="plateId" use="required"/>
		<xsd:attribute name="entryTime" type="xsd:dateTime" use="required"/>
		<xsd:attribute name="type" type="vType" use="required"/>
		<xsd:attribute name="state" type="vState" use="required"/>
		<xsd:attribute name="position" type="xsd:string" use="required"/><!-- ref -->
		<xsd:attribute name="origin" type="xsd:string" use="required"/><!-- ref -->
		<xsd:attribute name="destination" type="xsd:string" use="required"/><!-- ref -->
	</xsd:complexType>
	<xsd:complexType name="commonPlaceType">
		<xsd:sequence>
			<xsd:element name="nextPlace" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
		<xsd:attribute name="capacity" type="xsd:int" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="placeType">
		<xsd:complexContent>
			<xsd:extension base="commonPlaceType">
				<xsd:choice>
					<xsd:element name="roadSegment" type="roadSegmentType"/>
					<xsd:element name="parkingArea" type="parkingAreaType"/>
					<xsd:element name="gate" type="gateType"/>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="roadSegmentType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="road" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="parkingAreaType">
		<xsd:sequence>
			<xsd:element name="service" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- SIMPLE TYPES -->
	<xsd:simpleType name="plateId">
		<xsd:restriction base="xsd:string">
                <xsd:pattern value="[A-Z0-9]+"/>
         </xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="vType">
	  <xsd:restriction base="xsd:string">
	    <xsd:enumeration value="CAR"/>
	    <xsd:enumeration value="TRUCK"/>
	    <xsd:enumeration value="SHUTTLE"/>
	    <xsd:enumeration value="CARAVAN"/>
	  </xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="vState">
	  <xsd:restriction base="xsd:string">
	    <xsd:enumeration value="PARKED"/>
	    <xsd:enumeration value="IN_TRANSIT"/>
	  </xsd:restriction>
	</xsd:simpleType>
	 <xsd:simpleType name="gateType">
	  <xsd:restriction base="xsd:string">
	    <xsd:enumeration value="IN"/>
	    <xsd:enumeration value="OUT"/>
	    <xsd:enumeration value="INOUT"/>
	  </xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== NicolaSabino/DP2_Assignment1/temp1571746348/out2019579266.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<roadNavigationSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xsd/rnsInfo.xsd">
    <place capacity="1" id="Gate1">
        <gate>OUT</gate>
    </place>
    <place capacity="2" id="Gate2">
        <nextPlace>SS1-S0</nextPlace>
        <gate>INOUT</gate>
    </place>
    <place capacity="1" id="Gate0">
        <nextPlace>SS0-S0</nextPlace>
        <gate>IN</gate>
    </place>
    <place capacity="45" id="PA001">
        <nextPlace>SS0-S5</nextPlace>
        <parkingArea/>
    </place>
    <place capacity="45" id="PA000">
        <nextPlace>SS0-S0</nextPlace>
        <parkingArea>
            <service>Toilet</service>
        </parkingArea>
    </place>
    <place capacity="15" id="PA002">
        <nextPlace>SS1-S1</nextPlace>
        <parkingArea/>
    </place>
    <place capacity="18" id="PA004">
        <nextPlace>SS1-S4</nextPlace>
        <parkingArea>
            <service>Restaurant</service>
            <service>Toilet</service>
            <service>Bar</service>
        </parkingArea>
    </place>
    <place capacity="36" id="PA003">
        <nextPlace>SS1-S3</nextPlace>
        <parkingArea>
            <service>Toilet</service>
            <service>Bar</service>
        </parkingArea>
    </place>
    <place capacity="40" id="SS0-S0">
        <nextPlace>PA000</nextPlace>
        <nextPlace>SS0-S1</nextPlace>
        <roadSegment name="S0" road="SS0"/>
    </place>
    <place capacity="46" id="SS0-S2">
        <nextPlace>SS0-S3</nextPlace>
        <roadSegment name="S2" road="SS0"/>
    </place>
    <place capacity="46" id="SS0-S7">
        <nextPlace>Gate2</nextPlace>
        <roadSegment name="S7" road="SS0"/>
    </place>
    <place capacity="17" id="SS0-S6">
        <nextPlace>SS0-S7</nextPlace>
        <roadSegment name="S6" road="SS0"/>
    </place>
    <place capacity="10" id="SS0-S5">
        <nextPlace>PA001</nextPlace>
        <nextPlace>SS0-S6</nextPlace>
        <roadSegment name="S5" road="SS0"/>
    </place>
    <place capacity="48" id="SS1-S5">
        <nextPlace>SS1-S6</nextPlace>
        <roadSegment name="S5" road="SS1"/>
    </place>
    <place capacity="24" id="SS1-S7">
        <nextPlace>Gate1</nextPlace>
        <roadSegment name="S7" road="SS1"/>
    </place>
    <place capacity="41" id="SS0-S4">
        <nextPlace>SS0-S5</nextPlace>
        <roadSegment name="S4" road="SS0"/>
    </place>
    <place capacity="10" id="SS1-S1">
        <nextPlace>PA002</nextPlace>
        <nextPlace>SS1-S2</nextPlace>
        <roadSegment name="S1" road="SS1"/>
    </place>
    <place capacity="31" id="SS1-S4">
        <nextPlace>PA004</nextPlace>
        <nextPlace>SS1-S5</nextPlace>
        <roadSegment name="S4" road="SS1"/>
    </place>
    <place capacity="20" id="SS0-S1">
        <nextPlace>SS0-S2</nextPlace>
        <roadSegment name="S1" road="SS0"/>
    </place>
    <place capacity="12" id="SS1-S6">
        <nextPlace>SS1-S7</nextPlace>
        <roadSegment name="S6" road="SS1"/>
    </place>
    <place capacity="28" id="SS0-S3">
        <nextPlace>SS0-S4</nextPlace>
        <roadSegment name="S3" road="SS0"/>
    </place>
    <place capacity="28" id="SS1-S2">
        <nextPlace>SS1-S3</nextPlace>
        <roadSegment name="S2" road="SS1"/>
    </place>
    <place capacity="24" id="SS1-S0">
        <nextPlace>SS1-S1</nextPlace>
        <roadSegment name="S0" road="SS1"/>
    </place>
    <place capacity="15" id="SS1-S3">
        <nextPlace>PA003</nextPlace>
        <nextPlace>SS1-S4</nextPlace>
        <roadSegment name="S3" road="SS1"/>
    </place>
    <connection from="SS1-S1" to="PA002"/>
    <connection from="SS0-S7" to="Gate2"/>
    <connection from="SS0-S5" to="PA001"/>
    <connection from="Gate0" to="SS0-S0"/>
    <connection from="SS1-S3" to="PA003"/>
    <connection from="SS0-S4" to="SS0-S5"/>
    <connection from="SS0-S2" to="SS0-S3"/>
    <connection from="SS1-S4" to="PA004"/>
    <connection from="SS1-S1" to="SS1-S2"/>
    <connection from="SS1-S6" to="SS1-S7"/>
    <connection from="SS1-S0" to="SS1-S1"/>
    <connection from="SS0-S5" to="SS0-S6"/>
    <connection from="SS1-S7" to="Gate1"/>
    <connection from="PA000" to="SS0-S0"/>
    <connection from="SS1-S3" to="SS1-S4"/>
    <connection from="SS1-S5" to="SS1-S6"/>
    <connection from="Gate2" to="SS1-S0"/>
    <connection from="PA002" to="SS1-S1"/>
    <connection from="SS1-S2" to="SS1-S3"/>
    <connection from="SS0-S1" to="SS0-S2"/>
    <connection from="PA004" to="SS1-S4"/>
    <connection from="PA001" to="SS0-S5"/>
    <connection from="SS0-S6" to="SS0-S7"/>
    <connection from="PA003" to="SS1-S3"/>
    <connection from="SS0-S0" to="SS0-S1"/>
    <connection from="SS1-S4" to="SS1-S5"/>
    <connection from="SS0-S3" to="SS0-S4"/>
    <connection from="SS0-S0" to="PA000"/>
</roadNavigationSystem>

=== NicolaSabino/DP2_Assignment1/temp1016461478/out1642243003.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<roadNavigationSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xsd/rnsInfo.xsd">
    <place capacity="1" id="Gate1">
        <gate>OUT</gate>
    </place>
    <place capacity="2" id="Gate2">
        <nextPlace>A1-S0</nextPlace>
        <gate>INOUT</gate>
    </place>
    <place capacity="1" id="Gate0">
        <nextPlace>A0-S0</nextPlace>
        <gate>IN</gate>
    </place>
    <place capacity="26" id="PA000">
        <nextPlace>A1-S0</nextPlace>
        <parkingArea>
            <service>Restaurant</service>
        </parkingArea>
    </place>
    <place capacity="18" id="A0-S0">
        <nextPlace>A0-S1</nextPlace>
        <roadSegment name="S0" road="A0"/>
    </place>
    <place capacity="14" id="A1-S5">
        <nextPlace>Gate1</nextPlace>
        <roadSegment name="S5" road="A1"/>
    </place>
    <place capacity="12" id="A1-S3">
        <nextPlace>A1-S4</nextPlace>
        <roadSegment name="S3" road="A1"/>
    </place>
    <place capacity="46" id="A1-S4">
        <nextPlace>A1-S5</nextPlace>
        <roadSegment name="S4" road="A1"/>
    </place>
    <place capacity="12" id="A0-S1">
        <nextPlace>A0-S2</nextPlace>
        <roadSegment name="S1" road="A0"/>
    </place>
    <place capacity="11" id="A1-S1">
        <nextPlace>A1-S2</nextPlace>
        <roadSegment name="S1" road="A1"/>
    </place>
    <place capacity="15" id="A1-S0">
        <nextPlace>PA000</nextPlace>
        <nextPlace>A1-S1</nextPlace>
        <roadSegment name="S0" road="A1"/>
    </place>
    <place capacity="25" id="A1-S2">
        <nextPlace>A1-S3</nextPlace>
        <roadSegment name="S2" road="A1"/>
    </place>
    <place capacity="27" id="A0-S2">
        <nextPlace>Gate2</nextPlace>
        <roadSegment name="S2" road="A0"/>
    </place>
    <connection from="A1-S5" to="Gate1"/>
    <connection from="A1-S0" to="A1-S1"/>
    <connection from="Gate0" to="A0-S0"/>
    <connection from="PA000" to="A1-S0"/>
    <connection from="A1-S2" to="A1-S3"/>
    <connection from="A1-S4" to="A1-S5"/>
    <connection from="A1-S0" to="PA000"/>
    <connection from="A1-S1" to="A1-S2"/>
    <connection from="A0-S0" to="A0-S1"/>
    <connection from="A0-S1" to="A0-S2"/>
    <connection from="A0-S2" to="Gate2"/>
    <connection from="A1-S3" to="A1-S4"/>
    <connection from="Gate2" to="A1-S0"/>
</roadNavigationSystem>

=== NicolaSabino/DP2_Assignment1/temp1638915679/out1878563117.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<roadNavigationSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xsd/rnsInfo.xsd">
    <place capacity="1" id="Gate1">
        <gate>OUT</gate>
    </place>
    <place capacity="2" id="Gate2">
        <nextPlace>A0-S0</nextPlace>
        <gate>INOUT</gate>
    </place>
    <place capacity="1" id="Gate0">
        <nextPlace>SS0-S0</nextPlace>
        <gate>IN</gate>
    </place>
    <place capacity="24" id="PA001">
        <nextPlace>A0-S6</nextPlace>
        <parkingArea>
            <service>Restaurant</service>
        </parkingArea>
    </place>
    <place capacity="24" id="PA000">
        <nextPlace>SS0-S0</nextPlace>
        <parkingArea>
            <service>Bar</service>
        </parkingArea>
    </place>
    <place capacity="19" id="SS0-S0">
        <nextPlace>PA000</nextPlace>
        <nextPlace>SS0-S1</nextPlace>
        <roadSegment name="S0" road="SS0"/>
    </place>
    <place capacity="35" id="SS0-S1">
        <nextPlace>SS0-S2</nextPlace>
        <roadSegment name="S1" road="SS0"/>
    </place>
    <place capacity="30" id="SS0-S2">
        <nextPlace>Gate2</nextPlace>
        <roadSegment name="S2" road="SS0"/>
    </place>
    <place capacity="37" id="A0-S5">
        <nextPlace>A0-S6</nextPlace>
        <roadSegment name="S5" road="A0"/>
    </place>
    <place capacity="15" id="A0-S6">
        <nextPlace>PA001</nextPlace>
        <nextPlace>Gate1</nextPlace>
        <roadSegment name="S6" road="A0"/>
    </place>
    <place capacity="49" id="A0-S3">
        <nextPlace>A0-S4</nextPlace>
        <roadSegment name="S3" road="A0"/>
    </place>
    <place capacity="18" id="A0-S4">
        <nextPlace>A0-S5</nextPlace>
        <roadSegment name="S4" road="A0"/>
    </place>
    <place capacity="43" id="A0-S1">
        <nextPlace>A0-S2</nextPlace>
        <roadSegment name="S1" road="A0"/>
    </place>
    <place capacity="11" id="A0-S2">
        <nextPlace>A0-S3</nextPlace>
        <roadSegment name="S2" road="A0"/>
    </place>
    <place capacity="43" id="A0-S0">
        <nextPlace>A0-S1</nextPlace>
        <roadSegment name="S0" road="A0"/>
    </place>
    <connection from="A0-S0" to="A0-S1"/>
    <connection from="Gate0" to="SS0-S0"/>
    <connection from="SS0-S1" to="SS0-S2"/>
    <connection from="Gate2" to="A0-S0"/>
    <connection from="A0-S2" to="A0-S3"/>
    <connection from="A0-S4" to="A0-S5"/>
    <connection from="A0-S6" to="PA001"/>
    <connection from="A0-S6" to="Gate1"/>
    <connection from="A0-S1" to="A0-S2"/>
    <connection from="SS0-S0" to="SS0-S1"/>
    <connection from="SS0-S2" to="Gate2"/>
    <connection from="PA001" to="A0-S6"/>
    <connection from="A0-S3" to="A0-S4"/>
    <connection from="SS0-S0" to="PA000"/>
    <connection from="A0-S5" to="A0-S6"/>
    <connection from="PA000" to="SS0-S0"/>
</roadNavigationSystem>

=== NicolaSabino/DP2_Assignment1/error2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<roadNavigationSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xsd/rnsInfo.xsd">
    <place capacity="1" id="Gate1">
        <gate>OUT</gate>
    </place>
    <place capacity="2" id="Gate2">
        <gate>INOUT</gate>
    </place>
    <place capacity="1" id="Gate0">
        <gate>IN</gate>
    </place>
    <place capacity="19" id="PA002">
        <parkingArea>
            <service>Restaurant</service>
        </parkingArea>
    </place>
    <place capacity="46" id="PA001">
        <parkingArea>
            <service>Toilet</service>
            <service>Bar</service>
        </parkingArea>
    </place>
    <place capacity="30" id="PA000">
        <parkingArea>
            <service>Restaurant</service>
            <service>Toilet</service>
            <service>Bar</service>
        </parkingArea>
    </place>
    <place capacity="28" id="SS0-S0">
        <roadSegment name="S0" road="SS0"/>
    </place>
    <place capacity="32" id="SS0-S8">
        <roadSegment name="S8" road="SS0"/>
    </place>
    <place capacity="10" id="SS0-S9">
        <roadSegment name="S9" road="SS0"/>
    </place>
    <place capacity="27" id="A0-S6">
        <roadSegment name="S6" road="A0"/>
    </place>
    <place capacity="12" id="SS0-S1">
        <roadSegment name="S1" road="SS0"/>
    </place>
    <place capacity="50" id="SS0-S6">
        <roadSegment name="S6" road="SS0"/>
    </place>
    <place capacity="31" id="SS0-S7">
        <roadSegment name="S7" road="SS0"/>
    </place>
    <place capacity="21" id="SS0-S2">
        <roadSegment name="S2" road="SS0"/>
    </place>
    <place capacity="10" id="A0-S5">
        <roadSegment name="S5" road="A0"/>
    </place>
    <place capacity="31" id="A0-S3">
        <roadSegment name="S3" road="A0"/>
    </place>
    <place capacity="36" id="SS0-S5">
        <roadSegment name="S5" road="SS0"/>
    </place>
    <place capacity="48" id="A0-S7">
        <roadSegment name="S7" road="A0"/>
    </place>
    <place capacity="40" id="SS0-S3">
        <roadSegment name="S3" road="SS0"/>
    </place>
    <place capacity="23" id="SP0-S0">
        <roadSegment name="S0" road="SP0"/>
    </place>
    <place capacity="18" id="A0-S0">
        <roadSegment name="S0" road="A0"/>
    </place>
    <place capacity="50" id="SS0-S4">
        <roadSegment name="S4" road="SS0"/>
    </place>
    <place capacity="28" id="A0-S1">
        <roadSegment name="S1" road="A0"/>
    </place>
    <place capacity="43" id="A0-S4">
        <roadSegment name="S4" road="A0"/>
    </place>
    <place capacity="30" id="A0-S2">
        <roadSegment name="S2" road="A0"/>
    </place>
    <connection from="PA002" to="SS0-S9"/>
    <connection from="PA000" to="SS0-S6"/>
    <connection from="SP0-S0" to="Gate2"/>
    <connection from="Gate0" to="SS0-S0"/>
    <connection from="A0-S1" to="A0-S2"/>
    <connection from="SS0-S8" to="SS0-S9"/>
    <connection from="A0-S2" to="A0-S3"/>
    <connection from="SS0-S0" to="SS0-S1"/>
    <connection from="Gate2" to="A0-S0"/>
    <connection from="SS0-S5" to="SS0-S6"/>
    <connection from="Gate0" to="SP0-S0"/>
    <connection from="SS0-S7" to="SS0-S8"/>
    <connection from="A0-S6" to="A0-S7"/>
    <connection from="SS0-S4" to="SS0-S5"/>
    <connection from="SS0-S7" to="PA001"/>
    <connection from="SS0-S6" to="SS0-S7"/>
    <connection from="A0-S7" to="Gate1"/>
    <connection from="SS0-S9" to="Gate1"/>
    <connection from="A0-S0" to="A0-S1"/>
    <connection from="A0-S4" to="A0-S5"/>
    <connection from="PA001" to="SS0-S7"/>
    <connection from="SS0-S9" to="PA002"/>
    <connection from="SS0-S3" to="SS0-S4"/>
    <connection from="SS0-S6" to="PA000"/>
    <connection from="SS0-S1" to="SS0-S2"/>
    <connection from="A0-S5" to="A0-S6"/>
    <connection from="SS0-S2" to="SS0-S3"/>
    <connection from="A0-S3" to="A0-S4"/>
</roadNavigationSystem>

=== NicolaSabino/DP2_Assignment1/file.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<roadNavigationSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/rnsInfo.xsd">
    <place capacity="1" id="Gate1">
        <gate>OUT</gate>
    </place>
    <place capacity="2" id="Gate2">
        <nextPlace>A1-S0</nextPlace>
        <gate>INOUT</gate>
    </place>
    <place capacity="1" id="Gate0">
        <nextPlace>A0-S0</nextPlace>
        <nextPlace>SP0-S0</nextPlace>
        <gate>IN</gate>
    </place>
    <place capacity="26" id="PA000">
        <nextPlace>A0-S1</nextPlace>
        <parkingArea>
            <service>Toilet</service>
        </parkingArea>
    </place>
    <place capacity="28" id="A0-S0">
        <nextPlace>A0-S1</nextPlace>
        <roadSegment name="S0" road="A0"/>
    </place>
    <place capacity="18" id="A0-S2">
        <nextPlace>Gate1</nextPlace>
        <roadSegment name="S2" road="A0"/>
    </place>
    <place capacity="46" id="A0-S1">
        <nextPlace>PA000</nextPlace>
        <nextPlace>A0-S2</nextPlace>
        <roadSegment name="S1" road="A0"/>
    </place>
    <place capacity="50" id="SP0-S6">
        <nextPlace>SP0-S7</nextPlace>
        <roadSegment name="S6" road="SP0"/>
    </place>
    <place capacity="39" id="SP0-S0">
        <nextPlace>SP0-S1</nextPlace>
        <roadSegment name="S0" road="SP0"/>
    </place>
    <place capacity="41" id="SP0-S2">
        <nextPlace>SP0-S3</nextPlace>
        <roadSegment name="S2" road="SP0"/>
    </place>
    <place capacity="43" id="SP0-S4">
        <nextPlace>SP0-S5</nextPlace>
        <roadSegment name="S4" road="SP0"/>
    </place>
    <place capacity="31" id="A1-S2">
        <nextPlace>Gate1</nextPlace>
        <roadSegment name="S2" road="A1"/>
    </place>
    <place capacity="46" id="SP0-S5">
        <nextPlace>SP0-S6</nextPlace>
        <roadSegment name="S5" road="SP0"/>
    </place>
    <place capacity="41" id="A1-S0">
        <nextPlace>A1-S1</nextPlace>
        <roadSegment name="S0" road="A1"/>
    </place>
    <place capacity="49" id="SP0-S7">
        <nextPlace>Gate2</nextPlace>
        <roadSegment name="S7" road="SP0"/>
    </place>
    <place capacity="43" id="A1-S1">
        <nextPlace>A1-S2</nextPlace>
        <roadSegment name="S1" road="A1"/>
    </place>
    <place capacity="24" id="SP0-S1">
        <nextPlace>SP0-S2</nextPlace>
        <roadSegment name="S1" road="SP0"/>
    </place>
    <place capacity="34" id="SP0-S3">
        <nextPlace>SP0-S4</nextPlace>
        <roadSegment name="S3" road="SP0"/>
    </place>
    <connection from="SP0-S4" to="SP0-S5"/>
    <connection from="SP0-S0" to="SP0-S1"/>
    <connection from="SP0-S1" to="SP0-S2"/>
    <connection from="SP0-S2" to="SP0-S3"/>
    <connection from="A1-S2" to="Gate1"/>
    <connection from="Gate0" to="SP0-S0"/>
    <connection from="A1-S0" to="A1-S1"/>
    <connection from="Gate0" to="A0-S0"/>
    <connection from="SP0-S7" to="Gate2"/>
    <connection from="A0-S1" to="A0-S2"/>
    <connection from="Gate2" to="A1-S0"/>
    <connection from="A0-S1" to="PA000"/>
    <connection from="A1-S1" to="A1-S2"/>
    <connection from="A0-S0" to="A0-S1"/>
    <connection from="PA000" to="A0-S1"/>
    <connection from="A0-S2" to="Gate1"/>
    <connection from="SP0-S3" to="SP0-S4"/>
    <connection from="SP0-S5" to="SP0-S6"/>
    <connection from="SP0-S6" to="SP0-S7"/>
</roadNavigationSystem>
